# Generated by Django 2.2 on 2020-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='labels',
        ),
        migrations.AddField(
            model_name='contacts',
            name='labels',
            field=models.ManyToManyField(to='contacts.Label'),
        ),
    ]
