# Generated by Django 2.2 on 2020-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_dump',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
