# Generated by Django 2.2 on 2020-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_dump',
            name='vote_time',
            field=models.TextField(blank=True),
        ),
    ]
