# Generated by Django 2.2 on 2020-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_email_dump_vote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheetFromCommonNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.TextField()),
                ('group', models.CharField(max_length=50)),
                ('round', models.TextField()),
                ('game', models.CharField(max_length=5)),
                ('voted_for', models.CharField(max_length=50)),
                ('date', models.TextField()),
            ],
        ),
    ]
