# Generated by Django 2.2 on 2020-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_auto_20201127_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email_dump',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='email_dump',
            name='vote_time',
            field=models.TextField(blank=True),
        ),
    ]
