# Generated by Django 2.2 on 2020-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0003_datasheetfromcommonninja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetfromcommonninja',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
