# Generated by Django 2.2 on 2020-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0003_auto_20201127_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetfromcommonninja',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datasheetfromcommonninja',
            name='round',
            field=models.CharField(max_length=50),
        ),
    ]
