# Generated by Django 2.2 on 2020-11-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0004_auto_20201127_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetfromcommonninja',
            options={'ordering': ['id']},
        ),
    ]
