# Generated by Django 2.2 on 2020-11-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0004_auto_20201124_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheetfromcommonninja',
            old_name='date',
            new_name='date_time',
        ),
    ]
