# Generated by Django 2.2 on 2020-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0005_auto_20201127_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetfromcommonninja',
            name='vote_timestamp',
        ),
    ]
