# Generated by Django 2.2 on 2020-11-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0005_auto_20201124_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetfromcommonninja',
            name='date_time',
        ),
    ]
