# Generated by Django 2.2 on 2020-11-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0006_remove_datasheetfromcommonninja_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetfromcommonninja',
            name='date',
            field=models.TextField(blank=True),
        ),
    ]
