# Generated by Django 2.2 on 2020-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0007_datasheetfromcommonninja_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_dump',
            old_name='is_valid',
            new_name='invalid',
        ),
    ]
