# Generated by Django 2.2 on 2020-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_dump',
            name='email_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email_dump',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email_dump',
            name='varification_pending',
            field=models.BooleanField(default=True),
        ),
    ]
