# Generated by Django 2.2 on 2020-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0008_auto_20201128_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_dump',
            old_name='varification_pending',
            new_name='verification_pending',
        ),
        migrations.AddField(
            model_name='email_dump',
            name='email_verification_source',
            field=models.CharField(default='Not Yet', max_length=100),
        ),
    ]
