# Generated by Django 2.2 on 2020-11-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0009_auto_20201124_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_dump',
            name='vote_time',
            field=models.DateTimeField(),
        ),
    ]
