# Generated by Django 2.2 on 2020-11-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201127_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
    ]
