# Generated by Django 2.2 on 2020-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='event_text',
            field=models.CharField(default='Default event text', max_length=200),
        ),
    ]
