# Generated by Django 2.2 on 2020-12-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=50)),
                ('round', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=5)),
                ('voted_for', models.CharField(max_length=150)),
                ('vote_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datasheet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=50)),
                ('round', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=5)),
                ('voted_for', models.CharField(max_length=150)),
                ('vote_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'duplicate_votes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TempDatasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=50)),
                ('round', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=5)),
                ('voted_for', models.CharField(max_length=150)),
                ('vote_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temp_datasheet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TempVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('invalid', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('verification_pending', models.BooleanField(default=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent', models.IntegerField(default=0)),
                ('email_verification_source', models.CharField(default='Not Yet', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temp_voter',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('invalid', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('verification_pending', models.BooleanField(default=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent', models.IntegerField(default=0)),
                ('email_verification_source', models.CharField(default='Not Yet', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voter',
                'ordering': ['id'],
            },
        ),
    ]
