# Generated by Django 2.2 on 2020-12-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='voter_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upstaged_data.Voter'),
        ),
    ]
