# Generated by Django 2.2 on 2021-01-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('source', models.CharField(default='Not Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'voter_react',
                'verbose_name_plural': 'voter_reacts',
                'db_table': 'voter_react',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=30)),
                ('voted_for', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='upstaged_data.VoterReact')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'db_table': 'vote',
            },
        ),
    ]
