# Generated by Django 2.2 on 2020-12-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0002_datasheet_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='voter_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='upstaged_data.Voter'),
        ),
    ]
