# Generated by Django 2.2 on 2020-12-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0003_auto_20201201_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='voter_id',
        ),
    ]
