# Generated by Django 2.2 on 2020-12-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0005_fakedatasheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeDatasheet',
        ),
    ]
