# Generated by Django 2.2 on 2021-01-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upstaged_data', '0005_auto_20210104_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
